### ISSUE TITLE
Not going offline

### ISSUE THREAD

**Issue by ghost** [AnthonyAstige/ground-autoform#2]
Hi Anthony,

in my App it still doesn't go offline. It should also go with the _{{#autoForm ... }}_ tag, right, like so:

```
 {{#autoForm id="myForm" groundType="insert"  collection=myCollection}}
```

I have tried to clone your package locally and adding a console.log shows that the onSubmit changes are not called during startup of the App.

I also tried to add your onSubmit-hook directly to the form, still no success.
It inserts locally, but does not destroy the form and also the onSuccess-hook is only called later.

Any idea?

**Comment by AnthonyAstige** [comment]
Have you tried with a quickform? I don't recall if I tested with the general #autoForm.

I'm not really using this package so there could be issues with recent Meteor versions as well (I think I last used this on a Meteor 1.1 / 1.2 project that's locked).

**Comment by ghost** [comment]
No not yet. First I want to try to omit all the "type" arguments, maybe
that's the bug. Only then onSubmit should be evaluated.
But autoform kinda sucks. But since we utilized it for some forms, now
meteor does not recommend it anymore.
I write back when I tried this.

Am Donnerstag, 16. Juni 2016 schrieb Anthony Astige :

**Comment by ghost** [comment]
Hi there,

after an extensive look at the autoform package I think it doesn't go. In _autoform-events.js_ onSubmit is only called from the form type definition, there is neither if-clause whether the type is null 
( https://github.com/aldeed/meteor-autoform/blob/16f100ce96a13823b293414f5c615ea67693a39e/autoform-events.js#L319 )
nor is there a loading of the onSubmit from the global Hook Object (line 119ff):

```
// Gather hooks
```

nothing like:

```
      var onSubmitHooks = Hooks.getHooks(formId, 'onSubmit');
```

or alike.

The only way is probably to add it directly to FormTypes with:

```
AutoForm.addFormType('insert' / 'update', yourOnSubmitFunction)
```

Cheers

**Comment by ghost** [comment]
Ended up doing it with _AutoForm.addFormType()_.
In case anyone cares (rather follow the new Meteor Guidelines or go with React):
Just add the line:

```
 $(".back-button").click()
```

to the standard form types found in the _meteor-autoform/formTypes/_ directory (insert.js, update.js) when defining your own FormTypes.
